using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using UnityEngine;
using UnityEngine.Networking;

// =============================================================================
// CardImageLoader.cs
// =============================================================================
//
// PURPOSE
// -------
// This project intentionally does NOT commit any card art binaries to git
// (Bandai-owned IP + repo size concerns - see Tools/sync_sets.py header for
// the related set-data sync tool, which also leaves `cardImage` empty on
// newly generated CardVariable assets). Instead, card art is fetched at
// runtime from the `digimon-card-app` project (GitHub: lighttaker21/
// digimon-card-app), which already has real card art checked in under
// `src/assets/images/cards/{CARD_ID}.webp`.
//
// WHERE ART COMES FROM
// ---------------------
// For a given card id (e.g. "BT17-001" - this matches CardVariable.name,
// the ScriptableObject asset's own name, which Tools/sync_sets.py sets to
// the card's `id` field from PreparedDigimonCardsENG.json with any
// "_P0"/"_P1"/"-J"/"-Sample" variant suffix stripped), the base English art
// file is fetched from:
//
//     https://raw.githubusercontent.com/lighttaker21/digimon-card-app/main/src/assets/images/cards/{CARD_ID}.webp
//
// Variant arts (parallel/alt-art/Japanese) are NOT handled here - only the
// base id with no suffix, per current scope.
//
// LOCAL DISK CACHE
// -----------------
// Downloaded art is decoded once and cached as a PNG on disk at:
//
//     Application.persistentDataPath + "/CardImageCache/{CARD_ID}.png"
//
// This is OUTSIDE the git working tree (persistentDataPath is an
// OS-specific per-machine/per-install directory, never part of the repo),
// so no .gitignore entry is needed for it. On every subsequent run, if the
// cached PNG already exists, it is loaded directly from disk and no network
// request is made.
//
// WEBP DECODING STATUS - CAVEAT / BLOCKER
// -----------------------------------------
// digimon-card-app stores card art as .webp. Unity's built-in
// Texture2D.LoadImage / ImageConversion APIs do NOT support WebP - they only
// understand PNG/JPG/EXR/TGA. A search of this repo (Packages/manifest.json,
// Packages/packages-lock.json, Assets/Plugins) found NO existing WebP
// decoder, and none was vendored in here because Unity Package Manager
// network installs and native plugins cannot be verified to resolve/compile
// without launching the Unity Editor, which is not available in this
// environment.
//
// As a result, DecodeWebPToTexture2D() below currently throws
// NotSupportedException with a clear message instead of silently failing.
// The rest of the pipeline (download, cache-check, cache-write, Sprite
// assignment) is fully implemented and is NOT blocked - only the WebP byte
// decode step is.
//
// RECOMMENDED FOLLOW-UP (pick one):
//   1. Have digimon-card-app (or a small CI/server-side conversion step)
//      also publish PNG or JPG copies of card art at a parallel path/URL,
//      and switch DOWNLOAD_URL_TEMPLATE below to point at those instead.
//      This is the simplest fix and needs no Unity-side native code.
//   2. Vendor a tested, pure-C# WebP decoder package via Unity Package
//      Manager (e.g. a verified git-URL package) and implement
//      DecodeWebPToTexture2D() using it. Do this only once it can be
//      verified inside the actual Unity Editor, since UPM package
//      resolution cannot be confirmed from a non-Editor environment.
//
// USAGE
// -----
// Generic, keyed only by card id string - works for every set including
// future ones generated by Tools/sync_sets.py.
//
//     await CardImageLoader.LoadAndAssignAsync(cardVariable);
//
// or, to just get the Sprite without assigning it to a CardVariable:
//
//     Sprite sprite = await CardImageLoader.GetCardSpriteAsync(cardId);
//
// This mirrors the existing async/await style used by ImageGetData.cs
// (GetCardImageFromFile) rather than introducing a second coroutine-based
// convention.
// =============================================================================
public static class CardImageLoader
{
    private const string DownloadUrlTemplate =
        "https://raw.githubusercontent.com/lighttaker21/digimon-card-app/main/src/assets/images/cards/{0}.webp";

    private static string CacheDirectory => Path.Combine(Application.persistentDataPath, "CardImageCache");

    private static string CachedPngPath(string cardId) => Path.Combine(CacheDirectory, cardId + ".png");

    // Simple in-memory de-dupe so multiple simultaneous requests for the
    // same card id (e.g. several CardInCollection entries on screen at
    // once) don't each kick off their own download/decode.
    private static readonly Dictionary<string, Task<Sprite>> InFlightRequests = new();

    /// <summary>
    /// Loads (downloading + caching if necessary) the card art for the given
    /// CardVariable and assigns it to CardVariable.cardImage. Safe to call
    /// repeatedly; cached results are reused, and the underlying Sprite is
    /// the same type/field already consumed by RevealCardObject.cs,
    /// CardInCollection.cs, CardForBuildingDeckView.cs, etc.
    /// </summary>
    public static async Task LoadAndAssignAsync(CardVariable card)
    {
        if (card == null)
        {
            Debug.LogError("CardImageLoader.LoadAndAssignAsync called with a null CardVariable.");
            return;
        }

        string cardId = card.name;
        if (string.IsNullOrEmpty(cardId))
        {
            Debug.LogError("CardImageLoader: CardVariable has no name to use as a card id.");
            return;
        }

        Sprite sprite = await GetCardSpriteAsync(cardId);
        if (sprite != null)
        {
            card.cardImage = sprite;
        }
    }

    /// <summary>
    /// Returns the Sprite for a given card id, using the on-disk PNG cache
    /// if present, otherwise downloading the base English .webp art from
    /// digimon-card-app, decoding it, caching it as PNG, and converting it
    /// to a Sprite. Returns null (and logs) on any failure.
    /// </summary>
    public static Task<Sprite> GetCardSpriteAsync(string cardId)
    {
        if (string.IsNullOrEmpty(cardId))
        {
            Debug.LogError("CardImageLoader.GetCardSpriteAsync called with a null/empty card id.");
            return Task.FromResult<Sprite>(null);
        }

        if (InFlightRequests.TryGetValue(cardId, out Task<Sprite> existing))
        {
            return existing;
        }

        Task<Sprite> task = GetCardSpriteInternalAsync(cardId);
        InFlightRequests[cardId] = task;
        return task;
    }

    private static async Task<Sprite> GetCardSpriteInternalAsync(string cardId)
    {
        try
        {
            byte[] pngBytes;
            string cachePath = CachedPngPath(cardId);

            if (File.Exists(cachePath))
            {
                pngBytes = await ReadFileAsync(cachePath);
            }
            else
            {
                byte[] webpBytes = await DownloadBytesAsync(cardId);
                if (webpBytes == null)
                {
                    return null;
                }

                Texture2D decoded;
                try
                {
                    decoded = DecodeWebPToTexture2D(webpBytes);
                }
                catch (NotSupportedException ex)
                {
                    Debug.LogError(
                        $"CardImageLoader: cannot decode WebP art for card '{cardId}' - {ex.Message}");
                    return null;
                }

                if (decoded == null)
                {
                    Debug.LogError($"CardImageLoader: WebP decode returned null for card '{cardId}'.");
                    return null;
                }

                pngBytes = decoded.EncodeToPNG();
                UnityEngine.Object.Destroy(decoded);

                Directory.CreateDirectory(CacheDirectory);
                await WriteFileAsync(cachePath, pngBytes);
            }

            Texture2D tex = new Texture2D(2, 2, TextureFormat.RGBA32, false);
            if (!tex.LoadImage(pngBytes))
            {
                Debug.LogError($"CardImageLoader: failed to load cached PNG bytes for card '{cardId}'.");
                return null;
            }

            return Sprite.Create(tex, new Rect(0, 0, tex.width, tex.height), new Vector2(0.5f, 0.5f));
        }
        catch (Exception ex)
        {
            Debug.LogError($"CardImageLoader: unexpected error loading card '{cardId}': {ex}");
            return null;
        }
        finally
        {
            InFlightRequests.Remove(cardId);
        }
    }

    private static async Task<byte[]> DownloadBytesAsync(string cardId)
    {
        string url = string.Format(DownloadUrlTemplate, cardId);
        using UnityWebRequest request = UnityWebRequest.Get(url);
        request.downloadHandler = new DownloadHandlerBuffer();

        var operation = request.SendWebRequest();
        while (!operation.isDone)
        {
            await Task.Yield();
        }

#if UNITY_2020_1_OR_NEWER
        bool failed = request.result != UnityWebRequest.Result.Success;
#else
        bool failed = request.isNetworkError || request.isHttpError;
#endif
        if (failed)
        {
            Debug.LogError($"CardImageLoader: download failed for card '{cardId}' ({url}): {request.error}");
            return null;
        }

        return request.downloadHandler.data;
    }

    /// <summary>
    /// Decodes raw WebP-encoded bytes into a Texture2D.
    ///
    /// CURRENT STATUS: BLOCKED. Unity's built-in image APIs (Texture2D.
    /// LoadImage / ImageConversion) do not support WebP, and no WebP
    /// decoder package/plugin is currently vendored into this project (see
    /// the header comment block at the top of this file for why, and the
    /// two recommended follow-ups). Calling this throws NotSupportedException
    /// rather than silently failing or producing a blank/incorrect texture.
    /// </summary>
    private static Texture2D DecodeWebPToTexture2D(byte[] webpBytes)
    {
        throw new NotSupportedException(
            "WebP decoding is not yet implemented. Unity's Texture2D.LoadImage does not support " +
            "WebP. Either have digimon-card-app publish PNG/JPG art alongside the .webp files and " +
            "point CardImageLoader.DownloadUrlTemplate at those, or vendor a verified pure-C#/UPM " +
            "WebP decoder (verify package resolution inside the Unity Editor first). " +
            "See the header comment in CardImageLoader.cs for details.");
    }

    private static async Task<byte[]> ReadFileAsync(string path)
    {
        using FileStream fileStream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read, 4096, true);
        var buffer = new byte[fileStream.Length];
        int totalRead = 0;
        while (totalRead < buffer.Length)
        {
            int read = await fileStream.ReadAsync(buffer, totalRead, buffer.Length - totalRead);
            if (read <= 0) break;
            totalRead += read;
        }
        return buffer;
    }

    private static async Task WriteFileAsync(string path, byte[] bytes)
    {
        using FileStream fileStream = new FileStream(path, FileMode.Create, FileAccess.Write, FileShare.None, 4096, true);
        await fileStream.WriteAsync(bytes, 0, bytes.Length);
    }
}
