using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using UnityEngine;
using UnityEngine.Networking;

// =============================================================================
// CardImageLoader.cs
// =============================================================================
//
// PURPOSE
// -------
// This project intentionally does NOT commit any card art binaries to git
// (Bandai-owned IP + repo size concerns - see Tools/sync_sets.py header for
// the related set-data sync tool, which also leaves `cardImage` empty on
// newly generated CardVariable assets). Instead, card art is fetched at
// runtime from the `digimon-card-app` project (GitHub: lighttaker21/
// digimon-card-app), which has real card art checked in under
// `src/assets/images/cards/{CARD_ID}.webp` AND, as of digimon-card-app
// commit 903797c9 (scripts/python/Wiki/MoveFiles.py), a parallel raw-PNG
// export at `src/assets/images/cards-png/{CARD_ID}.png` specifically for
// consumers like this one that can't decode WebP.
//
// WHERE ART COMES FROM
// ---------------------
// For a given card id (e.g. "BT17-001" - this matches CardVariable.name,
// the ScriptableObject asset's own name, which Tools/sync_sets.py sets to
// the card's `id` field from PreparedDigimonCardsENG.json with any
// "_P0"/"_P1"/"-J"/"-Sample" variant suffix stripped), the base English art
// file is fetched from:
//
//     https://raw.githubusercontent.com/lighttaker21/digimon-card-app/main/src/assets/images/cards-png/{CARD_ID}.png
//
// Variant arts (parallel/alt-art/Japanese) are NOT handled here - only the
// base id with no suffix, per current scope.
//
// LOCAL DISK CACHE
// -----------------
// Downloaded art is cached as a PNG on disk at:
//
//     Application.persistentDataPath + "/CardImageCache/{CARD_ID}.png"
//
// This is OUTSIDE the git working tree (persistentDataPath is an
// OS-specific per-machine/per-install directory, never part of the repo),
// so no .gitignore entry is needed for it. On every subsequent run, if the
// cached PNG already exists, it is loaded directly from disk and no network
// request is made.
//
// WEBP CAVEAT - RESOLVED VIA SOURCE-SIDE PNG EXPORT
// ---------------------------------------------------
// Unity's built-in Texture2D.LoadImage / ImageConversion APIs do not support
// WebP, and no WebP decoder is vendored in this project. Rather than solve
// that on the Unity side, digimon-card-app's scrape pipeline was changed to
// also export a PNG copy of every card image it downloads, so this loader
// can just fetch PNG bytes directly and skip decoding entirely.
//
// CAVEAT: the PNG export only happens for cards (re-)scraped after
// digimon-card-app commit 903797c9. Cards whose wiki scrape predates that
// commit won't have a `cards-png/{id}.png` file until digimon-card-app's
// next scheduled refresh (its GitHub Action runs every 3 days, or can be
// triggered manually) re-downloads them. Until then, GetCardSpriteAsync
// will fail (404) for those specific cards and log an error rather than
// silently showing nothing.
//
// USAGE
// -----
// Generic, keyed only by card id string - works for every set including
// future ones generated by Tools/sync_sets.py.
//
//     await CardImageLoader.LoadAndAssignAsync(cardVariable);
//
// or, to just get the Sprite without assigning it to a CardVariable:
//
//     Sprite sprite = await CardImageLoader.GetCardSpriteAsync(cardId);
//
// This mirrors the existing async/await style used by ImageGetData.cs
// (GetCardImageFromFile) rather than introducing a second coroutine-based
// convention.
// =============================================================================
public static class CardImageLoader
{
    // digimon-card-app now also exports raw (pre-webp) PNGs alongside its
    // webp art, specifically so non-webp consumers like this project can
    // use them directly without a decoder (see digimon-card-app commit
    // 903797c9, scripts/python/Wiki/MoveFiles.py). This only takes effect
    // on cards (re-)scraped after that commit landed - cards whose wiki
    // scrape predates it won't have a PNG until the next refresh run.
    private const string DownloadUrlTemplate =
        "https://raw.githubusercontent.com/lighttaker21/digimon-card-app/main/src/assets/images/cards-png/{0}.png";

    private static string CacheDirectory => Path.Combine(Application.persistentDataPath, "CardImageCache");

    private static string CachedPngPath(string cardId) => Path.Combine(CacheDirectory, cardId + ".png");

    // Simple in-memory de-dupe so multiple simultaneous requests for the
    // same card id (e.g. several CardInCollection entries on screen at
    // once) don't each kick off their own download/decode.
    private static readonly Dictionary<string, Task<Sprite>> InFlightRequests = new();

    /// <summary>
    /// Loads (downloading + caching if necessary) the card art for the given
    /// CardVariable and assigns it to CardVariable.cardImage. Safe to call
    /// repeatedly; cached results are reused, and the underlying Sprite is
    /// the same type/field already consumed by RevealCardObject.cs,
    /// CardInCollection.cs, CardForBuildingDeckView.cs, etc.
    /// </summary>
    public static async Task LoadAndAssignAsync(CardVariable card)
    {
        if (card == null)
        {
            Debug.LogError("CardImageLoader.LoadAndAssignAsync called with a null CardVariable.");
            return;
        }

        string cardId = card.name;
        if (string.IsNullOrEmpty(cardId))
        {
            Debug.LogError("CardImageLoader: CardVariable has no name to use as a card id.");
            return;
        }

        Sprite sprite = await GetCardSpriteAsync(cardId);
        if (sprite != null)
        {
            card.cardImage = sprite;
        }
    }

    /// <summary>
    /// Returns the Sprite for a given card id, using the on-disk PNG cache
    /// if present, otherwise downloading the base English .webp art from
    /// digimon-card-app, decoding it, caching it as PNG, and converting it
    /// to a Sprite. Returns null (and logs) on any failure.
    /// </summary>
    public static Task<Sprite> GetCardSpriteAsync(string cardId)
    {
        if (string.IsNullOrEmpty(cardId))
        {
            Debug.LogError("CardImageLoader.GetCardSpriteAsync called with a null/empty card id.");
            return Task.FromResult<Sprite>(null);
        }

        if (InFlightRequests.TryGetValue(cardId, out Task<Sprite> existing))
        {
            return existing;
        }

        Task<Sprite> task = GetCardSpriteInternalAsync(cardId);
        InFlightRequests[cardId] = task;
        return task;
    }

    private static async Task<Sprite> GetCardSpriteInternalAsync(string cardId)
    {
        try
        {
            byte[] pngBytes;
            string cachePath = CachedPngPath(cardId);

            if (File.Exists(cachePath))
            {
                pngBytes = await ReadFileAsync(cachePath);
            }
            else
            {
                pngBytes = await DownloadBytesAsync(cardId);
                if (pngBytes == null)
                {
                    return null;
                }

                Directory.CreateDirectory(CacheDirectory);
                await WriteFileAsync(cachePath, pngBytes);
            }

            Texture2D tex = new Texture2D(2, 2, TextureFormat.RGBA32, false);
            if (!tex.LoadImage(pngBytes))
            {
                Debug.LogError($"CardImageLoader: failed to load cached PNG bytes for card '{cardId}'.");
                return null;
            }

            return Sprite.Create(tex, new Rect(0, 0, tex.width, tex.height), new Vector2(0.5f, 0.5f));
        }
        catch (Exception ex)
        {
            Debug.LogError($"CardImageLoader: unexpected error loading card '{cardId}': {ex}");
            return null;
        }
        finally
        {
            InFlightRequests.Remove(cardId);
        }
    }

    private static async Task<byte[]> DownloadBytesAsync(string cardId)
    {
        string url = string.Format(DownloadUrlTemplate, cardId);
        using UnityWebRequest request = UnityWebRequest.Get(url);
        request.downloadHandler = new DownloadHandlerBuffer();

        var operation = request.SendWebRequest();
        while (!operation.isDone)
        {
            await Task.Yield();
        }

#if UNITY_2020_1_OR_NEWER
        bool failed = request.result != UnityWebRequest.Result.Success;
#else
        bool failed = request.isNetworkError || request.isHttpError;
#endif
        if (failed)
        {
            Debug.LogError($"CardImageLoader: download failed for card '{cardId}' ({url}): {request.error}");
            return null;
        }

        return request.downloadHandler.data;
    }

    private static async Task<byte[]> ReadFileAsync(string path)
    {
        using FileStream fileStream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read, 4096, true);
        var buffer = new byte[fileStream.Length];
        int totalRead = 0;
        while (totalRead < buffer.Length)
        {
            int read = await fileStream.ReadAsync(buffer, totalRead, buffer.Length - totalRead);
            if (read <= 0) break;
            totalRead += read;
        }
        return buffer;
    }

    private static async Task WriteFileAsync(string path, byte[] bytes)
    {
        using FileStream fileStream = new FileStream(path, FileMode.Create, FileAccess.Write, FileShare.None, 4096, true);
        await fileStream.WriteAsync(bytes, 0, bytes.Length);
    }
}
